### ISSUE TITLE
Try to use cache for libraries installed with Conan

### ISSUE THREAD

**Issue by JacobDomagala** [JacobDomagala/Shady#108]
Consider something like this:

```yaml
    - name: Cache Conan packages
      id: cache-conan
      uses: actions/cache@v2
      with:
        path: ${{ env.CONAN_USER_HOME }}
        key: conan-cache-${{ hashFiles('**/conanfile.txt') }}
    - name: Install dependencies with Conan
      if: steps.cache-conan.outputs.cache-hit != 'true'
      run: |
      ```
